"use strict";

(function initializeVerifiedRunConstants(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.StarStrikeVerifiedRunConstants = api;
})(globalThis, function buildVerifiedRunConstants() {

const SIMULATION_HZ = 60;
const MAX_RUN_DURATION_SECONDS = 6 * 60 * 60;
const MAX_RUN_TICKS = SIMULATION_HZ * MAX_RUN_DURATION_SECONDS;
const MAX_INPUT_SEGMENTS = 250000;
const MAX_INPUT_BYTES = 2 * 1024 * 1024;
const CHECKPOINT_INTERVAL_TICKS = 600;
const MAX_CHECKPOINTS = Math.ceil(MAX_RUN_TICKS / CHECKPOINT_INTERVAL_TICKS);
const INPUT_MAGIC = "SSR1";
const INPUT_SCHEMA_VERSION = 1;
const INPUT_REVISION = "SSR_INPUT_V1";
const INPUT_HEADER_BYTES = 32;
const INPUT_SEGMENT_BYTES = 8;
const INPUT_CHECKPOINT_BYTES = 20;
const POSITION_UNITS_PER_PIXEL = 1024;
const ANGLE_UNITS = 4096;
const TRIG_UNITS = 1 << 20;
const ENERGY_UNITS_PER_POINT = 600;
const GAME_WIDTH_PIXELS = 375;
const GAME_HEIGHT_PIXELS = 667;
const GAME_WIDTH_UNITS = GAME_WIDTH_PIXELS * POSITION_UNITS_PER_PIXEL;
const GAME_HEIGHT_UNITS = GAME_HEIGHT_PIXELS * POSITION_UNITS_PER_PIXEL;
const SIMULATION_REVISION = "SSR_SIM_V1";

return Object.freeze({
  ANGLE_UNITS,
  CHECKPOINT_INTERVAL_TICKS,
  ENERGY_UNITS_PER_POINT,
  GAME_HEIGHT_PIXELS,
  GAME_HEIGHT_UNITS,
  GAME_WIDTH_PIXELS,
  GAME_WIDTH_UNITS,
  INPUT_CHECKPOINT_BYTES,
  INPUT_HEADER_BYTES,
  INPUT_MAGIC,
  INPUT_REVISION,
  INPUT_SCHEMA_VERSION,
  INPUT_SEGMENT_BYTES,
  MAX_CHECKPOINTS,
  MAX_INPUT_BYTES,
  MAX_INPUT_SEGMENTS,
  MAX_RUN_DURATION_SECONDS,
  MAX_RUN_TICKS,
  POSITION_UNITS_PER_PIXEL,
  SIMULATION_HZ,
  SIMULATION_REVISION,
  TRIG_UNITS
});
});
